/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceApresVenteRouteImport } from './routes/service-apres-vente'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProtectionDesDonneesPersonnellesRouteImport } from './routes/protection-des-donnees-personnelles'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ServiceApresVenteRoute = ServiceApresVenteRouteImport.update({
  id: '/service-apres-vente',
  path: '/service-apres-vente',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionDesDonneesPersonnellesRoute =
  ProtectionDesDonneesPersonnellesRouteImport.update({
    id: '/protection-des-donnees-personnelles',
    path: '/protection-des-donnees-personnelles',
    getParentRoute: () => rootRouteImport,
  } as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/boutique': typeof BoutiqueRoute
  '/commandes': typeof CommandesRoute
  '/compte': typeof CompteRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/protection-des-donnees-personnelles': typeof ProtectionDesDonneesPersonnellesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-apres-vente': typeof ServiceApresVenteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/boutique': typeof BoutiqueRoute
  '/commandes': typeof CommandesRoute
  '/compte': typeof CompteRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/protection-des-donnees-personnelles': typeof ProtectionDesDonneesPersonnellesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-apres-vente': typeof ServiceApresVenteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/boutique': typeof BoutiqueRoute
  '/commandes': typeof CommandesRoute
  '/compte': typeof CompteRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/protection-des-donnees-personnelles': typeof ProtectionDesDonneesPersonnellesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-apres-vente': typeof ServiceApresVenteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/blog'
    | '/boutique'
    | '/commandes'
    | '/compte'
    | '/contact'
    | '/favoris'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/protection-des-donnees-personnelles'
    | '/reset-password'
    | '/service-apres-vente'
    | '/blog/$slug'
    | '/categorie/$slug'
    | '/produit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/blog'
    | '/boutique'
    | '/commandes'
    | '/compte'
    | '/contact'
    | '/favoris'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/protection-des-donnees-personnelles'
    | '/reset-password'
    | '/service-apres-vente'
    | '/blog/$slug'
    | '/categorie/$slug'
    | '/produit/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/auth'
    | '/blog'
    | '/boutique'
    | '/commandes'
    | '/compte'
    | '/contact'
    | '/favoris'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/protection-des-donnees-personnelles'
    | '/reset-password'
    | '/service-apres-vente'
    | '/blog/$slug'
    | '/categorie/$slug'
    | '/produit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  BoutiqueRoute: typeof BoutiqueRoute
  CommandesRoute: typeof CommandesRoute
  CompteRoute: typeof CompteRoute
  ContactRoute: typeof ContactRoute
  FavorisRoute: typeof FavorisRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  ProtectionDesDonneesPersonnellesRoute: typeof ProtectionDesDonneesPersonnellesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiceApresVenteRoute: typeof ServiceApresVenteRoute
  CategorieSlugRoute: typeof CategorieSlugRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service-apres-vente': {
      id: '/service-apres-vente'
      path: '/service-apres-vente'
      fullPath: '/service-apres-vente'
      preLoaderRoute: typeof ServiceApresVenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection-des-donnees-personnelles': {
      id: '/protection-des-donnees-personnelles'
      path: '/protection-des-donnees-personnelles'
      fullPath: '/protection-des-donnees-personnelles'
      preLoaderRoute: typeof ProtectionDesDonneesPersonnellesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  BoutiqueRoute: BoutiqueRoute,
  CommandesRoute: CommandesRoute,
  CompteRoute: CompteRoute,
  ContactRoute: ContactRoute,
  FavorisRoute: FavorisRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  ProtectionDesDonneesPersonnellesRoute: ProtectionDesDonneesPersonnellesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiceApresVenteRoute: ServiceApresVenteRoute,
  CategorieSlugRoute: CategorieSlugRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
